//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hw__8
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class LibraryDb : DbContext
    {
        public LibraryDb()
            : base("name=LibraryDb")
        {
            Database.SetInitializer(new Initializer());
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<Author> Authors { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
    }

    public class Initializer : CreateDatabaseIfNotExists<LibraryDb>
    {
        protected override void Seed(LibraryDb context)
        {
            base.Seed(context);
            context.Books.Add(new Book()
            {
                Name = "Eneida",
                Pages = 266,
                AuthorId = 1
            });
            context.Books.Add(new Book()
            {
                Name = "Witcher",
                Pages = 100,
                AuthorId = 1
            });
            context.Books.Add(new Book()
            {
                Name = "kakaha",
                Pages = 40,
                AuthorId = 1
            });

            context.SaveChanges();

            context.Authors.Add(new Author()
            {
                Name = "Dale",
                Surname = "Carnegie",
                Age = 114

            });
            context.Authors.Add(new Author()
            {
                Name = "William",
                Surname = "Carnegie",
                Age = 114

            });

            context.SaveChanges();

            context.Countries.Add(new Country()
            {
                Name = "USA"
            });
            context.Countries.Add(new Country()
            {
                Name = "Britain"
            });

            context.SaveChanges();

            context.Languages.Add(new Language()
            {
                Name = "English",
                CountryId = 2
            });
            context.Languages.Add(new Language()
            {
                Name = "English (American)",
                CountryId = 1
            });

            context.SaveChanges();
        }
    }
}
